[package]
name = "octizys_cst"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
octizys_pretty={path="../octizys_pretty"}
octizys_common={path="../octizys_common"}
