[package]
name = "octizys_pretty"
version = "0.1.0"
edition = "2021"

[lib]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
octizys_text_store={path="../octizys_text_store"}
konst = "0.3.9"
string-interner = "0.17.0"
