[package]
name = "octizys_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
octizys_core = {path = "../octizys_core"}
octizys_sast = {path = "../octizys_sast"}

cfgrammar = "0.13"
lrlex = "0.13"
lrpar = "0.13"

[build-dependencies]
cfgrammar = "0.13"
lrlex = "0.13"
lrpar = "0.13"

[lints.rust]
unused = "allow"
unsafe_code = "forbid"
