[package]
name = "octizys_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
octizys_common = {path="../octizys_common"}

[lints.rust]
unused = "allow"
unsafe_code = "forbid"
